version: '3.7'
services:
  pdfsso:
    image: pdfsso:latest
    ports:
    - 9000:9000
    environment:
    - JWK_URL=https://core-qa.octanner.io/.well-known/jwks.json
    - GRAPH_QL_URL=https://identity2-core-qa.alamoapp.octanner.io/graphql
    - CORE_AUTH_CLIENT_ID=302f6bb7-c09e-48ab-9628-67311dcabd57
    - CORE_AUTH_CLIENT_SECRET=c1a919cce00a03c44004db923ef026e0e6fec09ed6ef0a0700d888a1dbd9fea7
    - TOKEN_URL=https://core-qa.octanner.io/sso/oauth/token
